stages:
  - build
  - test
  - package
  - publish

default:
  image: hectorlachambre/oc-expert-devops-java-python
  before_script:
    - chmod +x gradlew
    - apt-get update && apt-get install -y openjdk-21-jdk
    - export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))
    - export PATH=$JAVA_HOME/bin:$PATH

workflow:
  rules:
    - if: "$CI_COMMIT_BRANCH"

build_application:
  stage: build
  script:
    - python3 java-ci.py build
  artifacts:
    name: "ci-build-result"
    paths:
      - build/
    expire_in: 1 week

test_application:
  stage: test
  script:
    - python3 java-ci.py test
  artifacts:
    reports:
      junit: build/test-results/**/*.xml

package_application:
  stage: package
  script:
    - python3 java-ci.py pack
  artifacts:
    name: "ci-package-result"
    paths:
      - build/libs/*.war
    expire_in: 1 week

publish_application:
  stage: publish
  script:
    - python3 java-ci.py publish
  only:
    - main
  when: manual
