apiVersion: v1
kind: Service
metadata:
  name: workshop-organizer-db-service
spec:
  selector:
    app: workshop-organizer-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None
